name: CD

on:
  push:
    branches:
      - main
    tags:
      - v*.*

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and publish caphosra/${{ matrix.image }}

    strategy:
      fail-fast: false
      matrix:
        image:
          - ctf
          - haskell
          - ubuntu

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Look for a difference in the Docker file
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            ${{ matrix.image }}/Dockerfile

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        if: env.GIT_DIFF_FILTERED || startsWith(github.event.ref, 'refs/tags/v')

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: env.GIT_DIFF_FILTERED || startsWith(github.event.ref, 'refs/tags/v')

      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: env.GIT_DIFF_FILTERED || startsWith(github.event.ref, 'refs/tags/v')
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        if: env.GIT_DIFF_FILTERED || startsWith(github.event.ref, 'refs/tags/v')
        with:
          context: ./${{ matrix.image }}
          push: true
          tags: caphosra/${{ matrix.image }}:latest
